### ISSUE TITLE
iOS 13.2 breaks

### ISSUE THREAD

**Issue by Sydney-o9** [blockstack/blockstack-ios#90] opened 2019-11-10 08:51 UTC
Just reproducing the iOS SDK tutorial does not work on iOS 13.2. I'm using  `Blockstack 1.0.1`

```
Currently signed out so signing in.
MyApp(1094,0x10514d840) malloc: can't allocate region
*** mach_vm_map(size=6090375168) failed (error code=3)
MyApp(1094,0x10514d840) malloc: *** set a breakpoint in malloc_error_break to debug
```

![image](https://user-images.githubusercontent.com/1480617/68541424-68e51000-03f3-11ea-9096-c08f19dd12d0.png)

**Comment by shreyasthiagaraj** [comment] 2019-11-12 16:44
Is this an objective-c app?

**Comment by shreyasthiagaraj** [comment] 2019-11-25 23:20
Closing this as I cannot reproduce it.

**Closed as completed by shreyasthiagaraj** 2019-11-25 23:20 UTC
