### ISSUE TITLE
Sign in with Blockstack takes you to empty page with "?" on bottom right

### ISSUE THREAD

**Issue by shreyasthiagaraj** [blockstack/blockstack-ios#28] opened 2018-06-27 16:16 UTC
![simulator screen shot - iphone 6 - 2018-06-26 at 17 18 31](https://user-images.githubusercontent.com/8907863/41986373-3b4a4c5c-7a36-11e8-9c9a-7393b70b9529.png)

User petec description:
"Running into issues getting users authenticated in my iOS app or the example iOS app.  When I click the 'sign in with blockstack’ button in my app or the example iOS app it opens up a safari browser with url ‘browser.blockstack.org’ and all I see is a screen with a ? button in the lower right for the faqs and cancel in the upper left."

**Comment by larrysalibra** [comment] 2018-06-28 11:43
@shreyasthiagaraj I saw the same thing on android and it appears to be related to browser behavior verifying the manifest.json file of the app on slow network connections: https://github.com/blockstack/blockstack-browser/issues/1482

**Comment by yknl** [comment] 2018-06-28 13:43
This can also be caused by manifest files that are served over `http`. We need to improve the error handling in the Browser.

**Comment by aulneau** [comment] 2018-06-28 13:44
I can dig into this a bit today

**Comment by petec029** [comment] 2018-07-02 20:56
Just checking in to see if you were able to work on resolving this issue.  I know you recently released a new version of the browser so I wanted to let you know that I still get this empty screen with only the ? in the lower right when I run the iOS sample app or my own app using the Blockstack iOS SDK.  

If I just enter browser.blockstack.org in my phone's safari browser I see everything on the home screen  so not sure if the problem of signing in via a mobile app is related to this issue with SFAuthenticationSession. https://github.com/blockstack/blockstack-ios/issues/25
If so is there a workaround until you fix issue #25

**Comment by shreyasthiagaraj** [comment] 2018-07-05 12:33
@petec029 We are actively working on this and are very close to a fix. It will be be available with the next release of the browser (v0.30).

**Workaround for Emulator:**
On the emulator you can do Hardware -> Erase all content and settings. The same would work on a phone but of course that is not practical for a personal device.

The issue is discussed here in greater depth, if you'd like more context:
https://stackoverflow.com/questions/47207914/sfauthenticationsession-aswebauthenticationsession-and-logging-out

**Comment by petec029** [comment] 2018-07-09 15:30
Thanks @shreyasthiagaraj

**Comment by petec029** [comment] 2018-07-23 15:51
Hi @shreyasthiagaraj...I cleared the emulator as you suggested by doing a hardware -> erase all content and settings.  When I run the example iOS app and click sign in this time it brought me to a sign in page so I restored my blockstack userid.  But the next time I run the example iOS and click sign in the page goes right back to only seeing the ? in the lower right side.

**Comment by shreyasthiagaraj** [comment] 2018-07-23 18:49
@petec029 There is a secondary issue here. This problem is due to the fact that the example app requires a web app for auth and redirect. In ViewController.swift this should be defined as "http://localhost:8080/redirect.html". This is a bad value, and needs to be updated to an actual running web app. I'm currently having difficultly deploying something to fix this (something related to repository permissions). I'll try to have this taken care of by tomorrow and ping here when it's solved. 

Also, you can now just hit "sign out" instead of clearing emulator data every time.

**Comment by petec029** [comment] 2018-07-23 22:27
Thanks @shreyasthiagaraj

**Comment by shreyasthiagaraj** [comment] 2018-07-24 17:59
@petec029 This issue is now fixed in the **develop** branch.

**Comment by petec029** [comment] 2018-07-30 14:31
Hi @shreyasthiagaraj I tried out the develop branch and was able to successfully run the example iOS app on the Xcode simulator to sign in by restoring my Blockstack id and then giving Hello, Blockstack permissions to read my basic information.

I then tested signing out and clicked confirm when prompted to erase keychain and settings so you can create a new one or restore another keychain.  But now when I click Sign In with Blockstack and get to the hello, world website at browser.blockstack.org and click on Restore a Blockstack ID at the bottom of the screen nothing happens.  I have tried rerunning the example app and quitting out of the simulator and rerunning the example app but get the same result and can no longer restore a Blockstack id.

**Comment by shreyasthiagaraj** [comment] 2018-07-30 14:34
@petec029 That's interesting, I'll take a look at this issue today and try to get this resolved asap. Thanks for reporting it! For now a workaround is to clear the simulator content and settings.

**Comment by shreyasthiagaraj** [comment] 2018-08-03 16:28
I don't believe the new bug is related to this issue. I'm unable to reproduce it on the simulator or physical device, with either a .id or .id.blockstack name. Tracked here: https://github.com/blockstack/blockstack-browser/issues/1568

**Closed as completed** 2018-08-06 12:19 UTC
